export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAIL = 'GET_ORDER_DETAILS_FAIL';

export const ORDER_PAID_UPDATE_REQUEST = 'ORDER_PAID_UPDATE_REQUEST';
export const ORDER_PAID_UPDATE_SUCCESS = 'ORDER_PAID_UPDATE_SUCCESS';
export const ORDER_PAID_UPDATE_FAIL = 'ORDER_PAID_UPDATE_FAIL';
export const ORDER_PAID_UPDATE_RESET = 'ORDER_PAID_UPDATE_RESET';

export const GET_USER_ORDERS_REQUEST = 'GET_USER_ORDERS_REQUEST';
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS';
export const GET_USER_ORDERS_FAIL = 'GET_USER_ORDERS_FAIL';
export const GET_USER_ORDERS_RESET = 'GET_USER_ORDERS_RESET';