export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_INFO_REQUEST = 'PRODUCT_INFO_REQUEST';
export const PRODUCT_INFO_SUCCESS = 'PRODUCT_INFO_SUCCESS';
export const PRODUCT_INFO_FAIL = 'PRODUCT_INFO_FAIL';

export const CREATE_PRODUCT_REVIEW_REQUEST = 'CREATE_PRODUCT_REVIEW_REQUEST';
export const CREATE_PRODUCT_REVIEW_SUCCESS = 'CREATE_PRODUCT_REVIEW_SUCCESS';
export const CREATE_PRODUCT_REVIEW_FAIL = 'CREATE_PRODUCT_REVIEW_FAIL';
export const CREATE_PRODUCT_REVIEW_RESET = 'CREATE_PRODUCT_REVIEW_RESET';

// ADMIN 
export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL';

export const ADMIN_CREATE_NEW_PRODUCT_REQUEST = 'ADMIN_CREATE_NEW_PRODUCT_REQUEST';
export const ADMIN_CREATE_NEW_PRODUCT_SUCCESS = 'ADMIN_CREATE_NEW_PRODUCT_SUCCESS';
export const ADMIN_CREATE_NEW_PRODUCT_FAIL = 'ADMIN_CREATE_NEW_PRODUCT_FAIL';
export const ADMIN_CREATE_NEW_PRODUCT_RESET = 'ADMIN_CREATE_NEW_PRODUCT_RESET';

export const ADMIN_UPDATE_PRODUCT_REQUEST = 'ADMIN_UPDATE_PRODUCT_REQUEST';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAIL = 'ADMIN_UPDATE_PRODUCT_FAIL';
export const ADMIN_UPDATE_PRODUCT_RESET = 'ADMIN_UPDATE_PRODUCT_RESET';