// Login const
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
// register for a new account const
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
// get user profile details const
export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';
export const PROFILE_DETAILS_RESET = 'PROFILE_DETAILS_RESET';
// update user profile const
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET';
// get admin user list
export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST';
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL';
export const ADMIN_USER_LIST_RESET = 'ADMIN_USER_LIST_RESET';
// admin delete user 
export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAIL = 'ADMIN_DELETE_USER_FAIL';
// admin update user details 
export const ADMIN_UPDATE_USER_DETAILS_REQUEST = 'ADMIN_UPDATE_USER_DETAILS_REQUEST'
export const ADMIN_UPDATE_USER_DETAILS_SUCCESS = 'ADMIN_UPDATE_USER_DETAILS_SUCCESS'
export const ADMIN_UPDATE_USER_DETAILS_FAIL = 'ADMIN_UPDATE_USER_DETAILS_FAIL'
export const ADMIN_UPDATE_USER_DETAILS_RESET = 'ADMIN_UPDATE_USER_DETAILS_RESET'